/**CPPA Calculator**/
/**
How it works
Enter your course code 
Course unit
Score 
Grade is autogenerated
Weighted Point

**/

document.addEventListener("DOMContentLoaded",()=>{
    let courseCode = document.querySelector('course-code').value;
  });